### PR TITLE
feature: query/mutation variables are now interpreted as JSON

### PR DESCRIPTION
**Pull request by sullivtr**
This PR enhances mutation/query variable input by now interpreting values as JSON instead of just a string. 
For example:

BEFORE, only string values could be used for mutation variables: 
```hcl
mutation_variables = {
   "name" = "jimmy" // Just a string
   "otherVariable" = "otherValue" // Just a string
}
```

NOW, mutation variable values are interpreted as JSON when possible to support passing more complex data structures to GQL queries/mutations:
```hcl
mutation_variables = {
   "name" = "jimmy" // interpreted as a string
   "myListOfStrings" = "[ \"string1\", \"string2\" ]" // Interpreted as JSON: [ "string1", "string2" ]
   "myInt" = "123" // Interpreted as a number
  "myStringNumber" = "\"123\"" // Numbers that represent strings must be quoted --> interpreted as a string
}
```

As such, a full JSON object can be passed in as well:
```hcl
mutation_variables = {
   "myObject" = "{\"key\": \"value\"}"
}
```

### CODE REVIEW

**Comment by ajbouh** [comment]
Have you consider just making `mutation_variable_json` a string? Then you can expect users to use a single top-level jsonencode?

I don't feel strongly about this, but thought perhaps you hadn't considered it yet.

**Comment by sullivtr** [comment]
> Have you consider just making `mutation_variable_json` a string? Then you can expect users to use a single top-level jsonencode?
> 
> I don't feel strongly about this, but thought perhaps you hadn't considered it yet.

I did not want to modify the schema for this use-case. However, with this change, you will be able to use a top level JSON object in your mutation variables. So if your API expects an input object called a User!, then you can simple have a K:V in your mutation variables representing that User! object, and pass that along. (Unless I am misunderstanding what you mean)

**Comment by ajbouh** [comment]
It seems to me that if you're going to have some arrays or complex objects as variables then you'll have a lot of jsonencode calls... One for each value in `mutation_variables`.

This isn't a huge deal, but it will probably feel a bit clumsy. I expect I'll use a terraform map comprehension to avoid the boilerplate.

I'm more excited about getting this live than I am about slowing things down with a debate over the specifics though!

**Comment by sullivtr** [comment]
> It seems to me that if you're going to have some arrays or complex objects as variables then you'll have a lot of jsonencode calls... One for each value in `mutation_variables`.
> 
> This isn't a huge deal, but it will probably feel a bit clumsy. I expect I'll use a terraform map comprehension to avoid the boilerplate.
> 
> I'm more excited about getting this live than I am about slowing things down with a debate over the specifics though!

@ajbouh You won't have to use a bunch of separate jsonencode calls. Assuming you have a mutation that looks like this: 
```json
mutation createSomeThing( $input: SomeObjectType! )
  createSomeThing(input: $input) {
     . . .
  }
}
```

and the `SomeObjectType` has a structure like this: 
```json
{
   name: string
   items: []string
}
```

you can construct your mutation variables as: 
```hcl
mutation_variables = {
   "myObject" = "{ \"name\": \"some cool name\", \"items\": [ \"string1\", \"string2\" ] }" // This can be jsonencoded instead of writing inline, of course. 
}
```hcl

**Comment by ajbouh** [comment]
I see, yes. In the case that everything is being fed into a top-level `input` parameter you're absolutely right.

**Comment by sullivtr** [comment]
I expect to get this released this weekend. I want to let it soak for a bit as I test a few things

**Comment by sullivtr** [comment]
Sorry about delays in getting this released. My bandwidth has been limited lately, but I have not forgotten about this work.

**Comment by ajbouh** [comment]
I thought you made a recent release?

**Comment by sullivtr** [comment]
> I thought you made a recent release?

I have not made any releases that contain these changes yet. I did cut 1.5.0 recently, which adds the ability to compute mutation keys from objects inside of lists/arrays nested in json response.

**Comment by ajbouh** [comment]
Ah, ok. I am very excited for these changes to be in a release, but understand wanting to exercise caution.

**Comment by sullivtr** [comment]
@ajbouh I have just released an rc version for these changes if you want to go and try them out. That would be super helpful to me in validating these changes for a real use-case. My test env has shown success, but I need a more nuanced environment to test on, and your use-case would be a good test. There is a pre-release version to try this on, which will be `v2.0.0-rc`

**Pull request merged**
